# Nombre del paquete
package_name: modelo-saber2020

# Archivos de datos
train_data_file: saber2020_train_data.csv
test_data_file: saber2020_test_data.csv

# Variables
# Objetivo
target: PUNT_GLOBAL

features:
- COLE_JORNADA
- COLE_GENERO
- FAMI_EDUCACIONMADRE
- FAMI_EDUCACIONPADRE
- ESTU_TIENEETNIA
- FAMI_ESTRATOVIVIENDA
- FAMI_NUMLIBROS
- ESTU_DEDICACIONLECTURADIARIA
- FAMI_TIENEINTERNET
 

temp_features:
- ESTU_TIPODOCUMENTO
- ESTU_NACIONALIDAD
- ESTU_GENERO
- PERIODO
- ESTU_CONSECUTIVO
- ESTU_ESTUDIANTE
- ESTU_PAIS_RESIDE
- ESTU_TIENEETNIA
- ESTU_DEPTO_RESIDE
- ESTU_COD_RESIDE_DEPTO
- ESTU_MCPIO_RESIDE
- ESTU_COD_RESIDE_MCPIO
- FAMI_ESTRATOVIVIENDA
- FAMI_PERSONASHOGAR
- FAMI_CUARTOSHOGAR
- FAMI_EDUCACIONPADRE
- FAMI_EDUCACIONMADRE
- FAMI_TRABAJOLABORPADRE
- FAMI_TRABAJOLABORMADRE
- FAMI_TIENEINTERNET
- FAMI_TIENESERVICIOTV
- FAMI_TIENECOMPUTADOR
- FAMI_TIENELAVADORA
- FAMI_TIENEHORNOMICROOGAS
- FAMI_TIENEAUTOMOVIL
- FAMI_TIENEMOTOCICLETA
- FAMI_TIENECONSOLAVIDEOJUEGOS
- FAMI_NUMLIBROS
- FAMI_COMELECHEDERIVADOS
- FAMI_COMECARNEPESCADOHUEVO
- FAMI_COMECEREALFRUTOSLEGUMBRE
- FAMI_SITUACIONECONOMICA
- ESTU_DEDICACIONLECTURADIARIA
- ESTU_DEDICACIONINTERNET
- ESTU_HORASSEMANATRABAJA
- ESTU_TIPOREMUNERACION
- COLE_CODIGO_ICFES
- COLE_COD_DANE_ESTABLECIMIENTO
- COLE_NOMBRE_ESTABLECIMIENTO
- COLE_GENERO
- COLE_NATURALEZA
- COLE_CALENDARIO
- COLE_BILINGUE
- COLE_CARACTER
- COLE_COD_DANE_SEDE
- COLE_NOMBRE_SEDE
- COLE_SEDE_PRINCIPAL
- COLE_AREA_UBICACION
- COLE_JORNADA
- COLE_COD_MCPIO_UBICACION
- COLE_MCPIO_UBICACION
- COLE_COD_DEPTO_UBICACION
- COLE_DEPTO_UBICACION
- ESTU_PRIVADO_LIBERTAD
- ESTU_COD_MCPIO_PRESENTACION
- ESTU_MCPIO_PRESENTACION
- ESTU_DEPTO_PRESENTACION
- ESTU_COD_DEPTO_PRESENTACION
- PUNT_LECTURA_CRITICA
- PERCENTIL_LECTURA_CRITICA
- DESEMP_LECTURA_CRITICA
- PUNT_MATEMATICAS
- PERCENTIL_MATEMATICAS
- DESEMP_MATEMATICAS
- PUNT_C_NATURALES
- PERCENTIL_C_NATURALES
- DESEMP_C_NATURALES
- PUNT_SOCIALES_CIUDADANAS
- PERCENTIL_SOCIALES_CIUDADANAS
- DESEMP_SOCIALES_CIUDADANAS
- PUNT_INGLES
- PERCENTIL_INGLES
- DESEMP_INGLES
- PUNT_GLOBAL
- PERCENTIL_GLOBAL
- ESTU_ESTADOINVESTIGACION
- ESTU_GENERACION-E
- ESTU_INSE_INDIVIDUAL
- ESTU_NSE_INDIVIDUAL
- ESTU_NSE_ESTABLECIMIENTO
- ESTU_EDAD

# pipelines
pipeline_name: modelo-saber2020
pipeline_save_file: modelo-saber2020-output

# fracción del conjunto de prueba
test_size: 0.25

# semilla
random_state: 42

#Estrategia de Imputación
strategy: most_frequent

# hiperparámetros del modelo 
alpha: 0.001


# variables a mapear
qual_vars:
  - Attrition_Flag

# 
categorical_vars:
  - Attrition_Flag

# mapeo de variables
qual_mappings:
  Attrited Customer: 1
  Existing Customer: 0
